### ISSUE TITLE
Using different minimizer

### ISSUE THREAD

**Issue by BavyaBalakrishnan** [Boulder-Investment-Technologies/lppls#11]
I tried to use scipy.optimize.differential_evolution for optimization.
init_limits = [
                (tc_init_min, tc_init_max),  
                (0.1, 0.9),                  
                (6, 13),                     
            ]
cofs = differential_evolution(
                    func=self.func_restricted, bounds=init_limits, args=observations
                    
                    
                )

But its throwing some error. Can anyone point out the issue
![Screenshot from 2020-05-28 14-40-02](https://user-images.githubusercontent.com/15703094/83122473-52817600-a0f1-11ea-9b98-ed3563eeb91c.png)

**Comment by Joshwani** [comment]
Hi @BavyaBalakrishnan, currently the `fit` method will only support minimizers from `scipy.optimize.minimize` - they can be found [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html). If you fork the lppls repo and replace minimize with differential_evolution, you may be able to get a result. However it would involve more work than just replacing one optimizer with the other; the APIs for minimize and differential_evolution look a bit different.

From reviewing the [differential_evolution](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html) documentation, it looks like you don't start with an initial guess (`x0`) as you do with minimize. It also looks like `tc`, `m` and `w` would need to be passed to the objective function you're minimizing (`func_restricted`) via `args` instead of `bounds`.

Push up a branch if you want, I'd be happy to take a look.

Good luck!

**Comment by BavyaBalakrishnan** [comment]
Hi,
Thank you for your reply.
I made some changes,but in differential_evolution the f(x) is returning *nan.
*Any idea what could be the problem?
I have attached the modified code.

Regards

**Comment by Joshwani** [comment]
Hey @BavyaBalakrishnan, I'm not seeing the attached code. Can you create a branch within this repo?
